### Secteres using to store passwords
apiVersion: v1
kind: Secret     # we use secretes for storing my_sql password
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="